### ISSUE TITLE
[70$]Logout callback

### ISSUE THREAD

**Issue by gondzo** [topcoderinc/dsp-frontend#18]
When logging out, the dropdown doesn't always close and userInfo from local storage isn't cleared. UserInfo key is set in global.js and in AuthService.js, that should be refactored to a common method

**Comment by gvir** [comment]
Can we pick these issues ?

**Comment by gondzo** [comment]
yes, you can assign the issue to yourself

**Comment by gvir** [comment]
Took master branch , but log out button does not do anything functionality wise , so do we have to add the functionality of logging out ?

**Comment by birdofpreyru** [comment]
Hey, can I pick up this one? (It seems GitHub does not show me the option to self-assign myself, or I don't know where to look for it :)

**Comment by gondzo** [comment]
Logout button should remove the userInfo from local storage, clear the access token from the api service and close that dropdown

**Comment by gondzo** [comment]
If you are working on this, assign it to yourself in the right side pane (assignees section)

**Comment by birdofpreyru** [comment]
@gondzo I see you have created `issue-logout-callback` branch at the commit 171b4eea25297d849c98759a0ac63280db390dae, but don't you think it is better to work from the latest commit in the `dev` branch (f5d94cbace4c0d273cf8113746d20d48678c6b5b), as between those two commits a bunch of login related functionality have been merged in (judging by commit names)?

**Comment by gondzo** [comment]
I'm not sure what the issue-logout-callback branch was for, but I've forwarded it to dev. You can make a PR against dev too.

**Comment by gvir** [comment]
branch was made by me, will delete it, sorry for confusion

**Comment by birdofpreyru** [comment]
@gondzo Hey, will you check the above mentioned commit in my fork?

It fixes the dropdown, so that it is closed when you click `Profile` or `Logout` options.
It fixes the logout, so that user info is removed from the local storage, and once you click the `Logout` the header switches to the one corresponding to the `Not logged in` state.
Thus, it kind of solve the problem.

It does not do refactoring of the `AuthService` as (1) the service (like all other services in the app) is quite a mess, and it is quite a more big task to refactor it; (2) actually, now when you login with username/password, the `AuthService` is not used at all, everything is handled by the code in `global.js`. However, it seems that `AuthService` is used for social login functionality, so, as I told already, it is quite a separate big task to refactor everything that it uses `AuthService` in consistent way, and does not break anything.

**Comment by gondzo** [comment]
Looking at it right now.
As for the ApiService, there are quite a few challenges running in parallel, so I don't think we could manage to pull off refactoring for the ApiService.

**Comment by birdofpreyru** [comment]
Yeap. But, in future, it will be nice to implement a general APIService, which takes care about authorisation and staff, and allows to send any HTTP requests through it, not caring about the auth.

**Comment by gondzo** [comment]
Agreed.
This looks fine. Can you add a redirect to /home on logout and create a PR

**Comment by birdofpreyru** [comment]
Done

**Comment by gondzo** [comment]
Thanks

**Comment by kbowerma** [comment]
Payment Scheduled:   https://apps.topcoder.com/bugs/browse/DRONESERIES-7
